version: "3"
services:
  compute:
    image: {{IMAGE}}
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:  
      - simplest-sync:/home/jovyan/work/:nocopy 
    command: bash -c "cd /home/jovyan/work/ &&      
                      python setup.py develop &&         
                      jupyter lab --allow-root --NotebookApp.token=''"
             

volumes:
  simplest-sync:
    external: true
