version: "2.3"
services:
  compute:
    image: {{IMAGE}}
    ipc: "host"
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:  
      - simplest-sync:/home/jovyan/work/:nocopy 
    command: bash -c "cd /home/jovyan/work/ &&      
                      python setup.py develop &&         
                      jupyter lab --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"

volumes:
  simplest-sync:
    external: true
